apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deploy
  labels:
    app: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      name: customer
      labels:
        app: customer
    spec:
      containers:
        - name: customer-service
          image: manulc/customer-service:latest
          # En este caso, "Always" es el valor por defecto porque la versión de la imagen es latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
