apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deploy
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      name: notification
      labels:
        app: notification
    spec:
      containers:
        - name: notification-service
          image: manulc/notification-service
          # En este caso, "Always" es el valor por defecto porque la versión de la imagen es latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
