apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification
spec:
  # Valor por defecto si no se indica el tipo
  type: ClusterIP
  selector:
    app: notification
  ports:
    - port: 80
      targetPort: 8082
      